# Generated by Django 3.2 on 2021-04-25 22:26

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='image',
            field=models.ImageField(upload_to=upload.models.directory_path, verbose_name='Imagem'),
        ),
    ]
